### ISSUE TITLE
Support generation of Context Implementation on a type with derive macro

### ISSUE THREAD

**Issue by artech-git** [hashintel/hash#3531]
### Related Problem

Currently as per the documentation to enjoy the benefits of `Context` trait we have to manually implement it on our type as so
```rust
use error_stack::{Context, Result, ResultExt, Report};

#[derive(Debug)]
pub enum ConfigError {
    ParseError,
}
...
impl Context for ConfigError {}
```

### Proposed Solution

for large number of Custom error types it will make sense to have a derive macro available to perform the same thing

```rust
use error_stack::{Context, Result, ResultExt, Report};

#[derive(Debug, Context)] // generates the Context automatically
pub enum ConfigError {
    ParseError,
}
```

**Comment by TimDiekmann** [comment]
Hi @artech-git and thank you for the suggestion.

You're not the first person who asked for a derive macro. We have not implemented a derive macro, yet, because only deriving `Context` does not help, you need to implement `Display` as well, and that part is the far more harder thing to do. There are crates already to implement `Display` and if you use `thiserror` you also get an `Error` implementation, which implies a `Context` implementation. If we would provide a derive macro I like to cover providing values, so `provide()` will be implemented as well (if on a nightly toolchain). Also, when `Error` is available in `core` we're going to remove `Context` and replace it with `Error`.

If you currently want to derive `Context` I suggest you use [`thiserror` ](https://crates.io/crates/thiserror) and derive `Error`. We eventually want to provide a derive macro and also already [reserved a crate](https://crates.io/crates/error-stack-macros) for that but currently, this is not planned.
