### ISSUE TITLE
Clone Report?

### ISSUE THREAD

**Issue by tisonkun** [hashintel/hash#4610]
### Related Problem

I have a query result in type `error_stack::Result<ResultSet, MyError>`.

I may return the result multiple times but found that error-stask's Report is not Clone and prevent me to return a clone of it each time.

### Proposed Solution

Is there any blockers to implement `Clone` for `Report`? Or how can I return the same "failable ResultSet" multiple times here.

**Comment by TimDiekmann** [comment]
Hi @tisonkun and thanks for opening the issue.

The main blocker to implement `Clone` is that `Report` can store any kind of errors, even if they don't implement `Clone`. Quite a few common errors (i.e. `io::Error`) do not implement `Clone`, so it would make these errors impossible to use.

The idea of using an `Arc` is interesting but it won't work either because then the frames would become immutable (solvable for reports without any clones, but as soon as you clone your report you couldn't modify your frames gain). Mutability is important so you can use `downcast_mut` or `frames_mut` e.g. for hiding information in your report (e.g. masking passwords). 

If you need to pass your report to multiple locations can't you create an `Arc<Report<...>>`?

**Comment by tisonkun** [comment]
> If you need to pass your report to multiple locations can't you create an Arc<Report<...>>?

This sounds good; until I found that sometime I need to `change_context` still on the returned Result.

Currently, I use a workaround like:

```rust
Err(err: &Report<CommondErrpr>) => Err(report!(CommandError(err.to_string()))),
```

But perhaps it's my domain model's issue ...

**Comment by vilkinsons** [comment]
@tisonkun Thanks for taking a look at this in any case! Glad you managed to arrive at a working solution.
