### ISSUE TITLE
OptionExt to chain errors

### ISSUE THREAD

**Issue by tisonkun** [hashintel/hash#4777]
### Proposed Solution

Things like snafu's OptionExt - https://docs.rs/snafu/latest/snafu/trait.OptionExt.html

```rust
let make_error = || Error::Internal(format!("failed to submit query: {query}"));
optional_result.change_context_lazy(make_error)
```

Currently, we can use `ok_or_else(make_error)?` and there is an auto `Into`. But an OptionExt should provide more ergonomic practice.

**Comment by TimDiekmann** [comment]
Hi @tisonkun and thanks for asking!

Actually, we actively decided _against_ an `OptionExt`. We had this before, but removed it before we initially released `error-stack`. The reason is the [same as in `eyre`](https://docs.rs/eyre/0.6.8/eyre/index.html#context-and-option): An option does not have a context, so `change_context` or `attach` does not really make sense here. It would be possible to create an `OptionExt` which provides `optional.ok_or_report(error)` and `optional.ok_or_report_lazy(make_error)`, but this basically is the same as `optional.ok_or(Report::new(error))` and `optional.ok_or_else(make_error).map_err(Report::new)` and I'm not sure if the overhead of (a) importing `OptionExt` and (b) learning another API just to safe a few characters is really worth it, I tend to avoid this.

Another reason is the semantic meaning of an option. We only want to create reports for errors, but an optional value is not an error, it needs to be made into an error in order to pack it into a report.

**Comment by indietyp** [comment]
I can only echo on @TimDiekmann, especially because of the - aforementioned - semantic meaning `change_context` indicates that we already have a report, we're simply changing the context of said report. That isn't the case with an `Option`, in that case we would would be **creating** a new `Report`, not changing it.

I don't really see the benefit of something like `OptionExt`, sure it would make writing `ok_or_else(|| Report::new(..))` a bit more terse, but the downside is twofold:
* you have yet another trait import
* you have additional cognitive load for people new to the codebase that are maybe unfamiliar with `error-stack`

Everyone known `ok_or_else`, that wouldn't be the case with `ok_or_report` (or something similar).

**Comment by tisonkun** [comment]
Thanks for your answers. All is fair point :D

Closed as won't do.
