### ISSUE TITLE
error-stack: Provide an OptionExt to create reports with a given context for Option::None

### ISSUE THREAD

**Issue by jnicholls** [hashintel/hash#667]
I think this would be nice to have vs. `ok_or_else()` + deliberate `Report::new()`

**Comment by jnicholls** [comment]
Quickly created this issue on my phone, while I was thinking about it. If you accept contributions I’d be happy to contribute this, if you all are amenable to the idea.

**Comment by TimDiekmann** [comment]
Hi @jnicholls! Thanks for the issue, and, yes, we'd love to see contributions!

However, we intentionally did not provide `OptionExt` to convert `Option::None` to `Report`. This decision was made because an `Option` does not have an error to create a `Report` from (this is the same reason, why [`eyre` does not provide it](https://docs.rs/eyre/latest/eyre/index.html#context-and-option)).

**Comment by tisonkun** [comment]
@TimDiekmann  eyre has an OptionExt::ok_or_eyre So I'd expect something like OptionExt::ok_or_report(IntoReport)

See https://github.com/fast/exn/commit/cf0bc9da5f257654c18150aa736dce0834917dd3.

**Comment by TimDiekmann** [comment]
I actually never thought about `ok_or_report`. A quite low-hanging fruit without unambiguity. Let's just do it!

**Comment by TimDiekmann** [comment]
Are there any open-source volunteers available? I’m unlikely to be able to work on it in the next 1-2 weeks.
