### ISSUE TITLE
Mismatch example and release version of `error-stack`

### ISSUE THREAD

**Issue by BobAnkh** [hashintel/hash#749]
Hi, really glad to have the useful lib `error-stack`. Here maybe small mismatch:

While the examples in README.md and `examples` folder are all using `into_report()` in the mainline code, the release version `v0.1.1` in crates.io and the corresponding documentations are using `report()`. So it might be helpful to release a new version of `error-stack` to match the example and README.

Just a minor suggestion.

**Comment by Alfred-Mountfield** [comment]
As you've identified, we use the pretty common pattern of letting the state of the main branch move ahead of releases (which is otherwise less convenient to do in a monorepo). To see the documentation around the released version of `error-stack` we are expecting most people to look at crates.io and docs.rs (as you've identified).

With regards to the mismatch, this is just how the pattern works and is to be expected. We haven't published a release yet with the `report`/`into_report` changes because it will require breaking changes and we'd like to stack some other changes into that release first. As such it's a conscious decision to not do so at present :)

You do bring up a good point about the `examples` folder being a little confusing, it is possible to access the right version [through docs.rs](https://docs.rs/crate/error-stack/latest/source/examples/), but it's not easy to find. We will look into if it's possible to easily link to this in the docs, but we'll also think about other strategies to make it easier for people to identify the commit associated with the release. Using GitHub releases is a bit messy in a monorepo so we'll think about using tags or something else.

Going to close as I think it was mostly about suggesting a release, but we're definitely open to suggestions about how we can improve discoverability of the docs and such.
Hope that makes sense!
